'use strict';
// All UI strings. Language: settings.language = 'system' | 'en' | 'ru'.
// t(key, ...args) substitutes {0}, {1}, …

const DICTS = {
  en: {
    // tray
    trayTooltip: 'Shotik — screenshots for humans & AI',
    trayRegion: 'Capture area',
    trayFull: 'Capture screen',
    trayRepeat: 'Repeat last area',
    trayOpen: 'Open Shotik',
    trayQuit: 'Quit',
    // toasts
    copiedTitle: 'Copied to clipboard',
    noSave: 'Not saved to disk',
    claudeTitle: 'Ready for Claude',
    claudeBody: 'Ctrl+V in the console — pastes the image or the path',
    savedTitle: 'Saved',
    screenCopied: 'Screen copied',
    ocrDoneTitle: 'Text recognized and copied',
    ocrTitle: 'OCR',
    ocrNoText: 'No text found',
    ocrFailTitle: 'OCR failed',
    noLastTitle: 'No last area yet',
    noLastBody: 'Take an area screenshot first ({0})',
    repeatTitle: 'Area re-captured',
    colorTitle: 'Color copied',
    mcpFailTitle: 'MCP server failed to start',
    mcpFailBody: 'Port {0}: {1}',
    // pin context menu
    pinCopy: 'Copy image',
    pinSaveAs: 'Save as…',
    pinReveal: 'Show in folder',
    pinOpacity: 'Opacity {0}%',
    pinReset: 'Original size (100%)',
    pinClose: 'Close',
    // mac permission dialog
    permTitle: 'Shotik needs Screen Recording access',
    permBody: 'System Settings → Privacy & Security → Screen Recording → enable Shotik, then restart the app.',
    // overlay
    hintDrag: 'Drag', hintDragDesc: 'select area',
    hintClick: 'Click', hintClickDesc: 'window / screen',
    hintAlt: 'Alt', hintAltDesc: 'ignore windows',
    hintColor: 'C', hintColorDesc: 'pick pixel color',
    hintEsc: 'Esc', hintEscDesc: 'cancel',
    claudeBadge: 'Claude is waiting — select an area and confirm',
    toolMove: 'Select (1)', toolPen: 'Pen (2)', toolArrow: 'Arrow (3)', toolLine: 'Line (4)',
    toolRect: 'Box (5)', toolEllipse: 'Ellipse (6)', toolHighlight: 'Highlighter (7)',
    toolBlur: 'Pixelate (8)', toolText: 'Text (9)', toolCounter: 'Numbering (0)',
    tipUndo: 'Undo (Ctrl+Z)', tipRedo: 'Redo (Ctrl+Y)',
    tipOcr: 'Recognize text (T)', tipPin: 'Pin on top (P)', tipSave: 'Save as… (Ctrl+S)',
    tipClaude: 'Copy for Claude (A)', tipCopy: 'Copy (Enter)', tipCancel: 'Cancel (Esc)',
    tipThin: 'Thin ([)', tipMedium: 'Medium', tipThick: 'Thick (])',
    // app: nav & gallery
    navShots: 'Shots', navClaude: 'Claude', navSettings: 'Settings',
    logoSub: 'screenshots for humans & AI',
    shotsTitle: 'Shots',
    btnRegion: 'Area', btnFull: 'Screen', btnRepeat: 'Repeat',
    tipRepeatBtn: 'Re-capture the last area — same coordinates, fresh pixels',
    tipOpenDir: 'Open screenshots folder',
    emptyTitle: 'No screenshots yet',
    emptyBody: 'Press {0} anytime — select an area and it lands<br>in your clipboard and in this gallery.',
    srcRegion: 'area', srcFullscreen: 'screen', srcRepeat: 'repeat', srcMcp: 'Claude', srcPin: 'pin',
    justNow: 'just now', minAgo: '{0} min ago', hourAgo: '{0} h ago',
    actCopy: 'Copy', actPath: 'Path', actPin: 'Pin', actOcr: 'OCR', actFolder: 'Folder', actDelete: 'Delete',
    // app: claude page
    claudePageTitle: 'Claude can see your screen',
    mcpCardTitle: 'Built-in MCP server',
    mcpRunning: 'Running at <b>http://127.0.0.1:{0}/mcp</b>',
    mcpNotRunning: 'Not running — the port may be busy',
    mcpDisabled: 'Disabled',
    connectTitle: 'Connect to Claude Code', connectOnce: 'one time',
    connectSub: 'After this, Claude can take screenshots of your screen by itself.',
    btnCopyCmd: 'Copy', btnCopiedCmd: 'Copied ✓',
    toolsTitle: 'What Claude can do through Shotik',
    toolDesc1: 'look at the screen right now',
    toolDesc2: 'ask you to select an area',
    toolDesc3: 'grab your latest screenshot',
    hintBox: '💡 A copied screenshot pastes into Claude Code as an image (<kbd>Ctrl+V</kbd>), and into a regular terminal as a file path. That’s Smart Clipboard: both formats go to the clipboard at once.',
    logTitle: 'Call log',
    logEmpty: 'Claude hasn’t called Shotik yet',
    logMs: '{0} ms',
    // app: settings page
    settingsTitle: 'Settings',
    hkTitle: 'Hotkeys',
    hkRegion: 'Capture area', hkRegionSub: 'selection with annotations',
    hkFull: 'Full screen', hkFullSub: 'monitor under the cursor, straight to clipboard',
    hkRepeat: 'Repeat last area', hkRepeatSub: 'same area, fresh pixels — perfect for iterating with Claude',
    hkPlaceholder: 'press a shortcut',
    hkRecording: 'press keys… (Esc — cancel, Del — clear)',
    hkWarn: '⚠ Failed to register: {0} — the shortcut is taken by another app.',
    saveTitle: 'Saving',
    saveDir: 'Screenshots folder', btnChange: 'Change',
    autoSave: 'Auto-save', autoSaveSub: 'every shot is written to the folder immediately',
    clipTitle: 'Clipboard & convenience',
    smartClip: 'Smart Clipboard', smartClipSub: 'image + file path in the clipboard at the same time',
    toasts: 'Notifications', toastsSub: 'toast after every capture',
    downscale: 'Compress shots for AI', downscaleSub: 'MCP serves ≤1600px — faster and cheaper for Claude',
    autostart: 'Start with Windows', autostartSub: 'silent start in the tray',
    language: 'Language', languageSub: 'interface language',
    langSystem: 'System',
    mcpSettingsTitle: 'MCP server',
    port: 'Port', portSub: 'restarts automatically',
  },

  ru: {
    trayTooltip: 'Shotik — скриншоты для людей и AI',
    trayRegion: 'Снимок области',
    trayFull: 'Весь экран',
    trayRepeat: 'Переснять область',
    trayOpen: 'Открыть Shotik',
    trayQuit: 'Выход',
    copiedTitle: 'Скопировано в буфер',
    noSave: 'Без сохранения',
    claudeTitle: 'Готово для Claude',
    claudeBody: 'Ctrl+V в консоль — вставится картинка или путь',
    savedTitle: 'Сохранено',
    screenCopied: 'Экран скопирован',
    ocrDoneTitle: 'Текст распознан и скопирован',
    ocrTitle: 'OCR',
    ocrNoText: 'Текст не найден',
    ocrFailTitle: 'OCR не сработал',
    noLastTitle: 'Нет последней области',
    noLastBody: 'Сначала сделай снимок области ({0})',
    repeatTitle: 'Область переснята',
    colorTitle: 'Цвет скопирован',
    mcpFailTitle: 'MCP-сервер не запустился',
    mcpFailBody: 'Порт {0}: {1}',
    pinCopy: 'Копировать изображение',
    pinSaveAs: 'Сохранить как…',
    pinReveal: 'Открыть в папке',
    pinOpacity: 'Прозрачность {0}%',
    pinReset: 'Исходный размер (100%)',
    pinClose: 'Закрыть',
    permTitle: 'Shotik нужен доступ к записи экрана',
    permBody: 'Системные настройки → Конфиденциальность и безопасность → Запись экрана → включить Shotik, затем перезапустить приложение.',
    hintDrag: 'Тяни', hintDragDesc: 'область',
    hintClick: 'Клик', hintClickDesc: 'окно / экран',
    hintAlt: 'Alt', hintAltDesc: 'без привязки',
    hintColor: 'C', hintColorDesc: 'цвет пикселя',
    hintEsc: 'Esc', hintEscDesc: 'отмена',
    claudeBadge: 'Claude ждёт область — выдели и подтверди',
    toolMove: 'Выделение (1)', toolPen: 'Перо (2)', toolArrow: 'Стрелка (3)', toolLine: 'Линия (4)',
    toolRect: 'Рамка (5)', toolEllipse: 'Эллипс (6)', toolHighlight: 'Маркер (7)',
    toolBlur: 'Пикселизация (8)', toolText: 'Текст (9)', toolCounter: 'Нумерация (0)',
    tipUndo: 'Отменить (Ctrl+Z)', tipRedo: 'Вернуть (Ctrl+Y)',
    tipOcr: 'Распознать текст (T)', tipPin: 'Закрепить поверх окон (P)', tipSave: 'Сохранить как… (Ctrl+S)',
    tipClaude: 'Скопировать для Claude (A)', tipCopy: 'Копировать (Enter)', tipCancel: 'Отмена (Esc)',
    tipThin: 'Тонко ([)', tipMedium: 'Средне', tipThick: 'Толсто (])',
    navShots: 'Снимки', navClaude: 'Claude', navSettings: 'Настройки',
    logoSub: 'скриншоты для людей и AI',
    shotsTitle: 'Снимки',
    btnRegion: 'Область', btnFull: 'Экран', btnRepeat: 'Переснять',
    tipRepeatBtn: 'Переснять последнюю область — те же координаты, свежие пиксели',
    tipOpenDir: 'Открыть папку со снимками',
    emptyTitle: 'Пока нет снимков',
    emptyBody: 'Нажми {0} в любой момент — выдели область, и она окажется<br>в буфере обмена и в этой галерее.',
    srcRegion: 'область', srcFullscreen: 'экран', srcRepeat: 'повтор', srcMcp: 'Claude', srcPin: 'pin',
    justNow: 'только что', minAgo: '{0} мин назад', hourAgo: '{0} ч назад',
    actCopy: 'Копировать', actPath: 'Путь', actPin: 'Закрепить', actOcr: 'OCR', actFolder: 'В папке', actDelete: 'Удалить',
    claudePageTitle: 'Claude видит твой экран',
    mcpCardTitle: 'Встроенный MCP-сервер',
    mcpRunning: 'Работает на <b>http://127.0.0.1:{0}/mcp</b>',
    mcpNotRunning: 'Не запустился — возможно, порт занят',
    mcpDisabled: 'Выключен',
    connectTitle: 'Подключение к Claude Code', connectOnce: 'один раз',
    connectSub: 'После этого Claude сможет сам делать скриншоты твоего экрана.',
    btnCopyCmd: 'Копировать', btnCopiedCmd: 'Скопировано ✓',
    toolsTitle: 'Что умеет Claude через Shotik',
    toolDesc1: 'посмотреть на экран прямо сейчас',
    toolDesc2: 'попросить тебя выделить область',
    toolDesc3: 'взять твой последний снимок',
    hintBox: '💡 Скопированный снимок вставляется в Claude Code как картинка (<kbd>Ctrl+V</kbd>), а в обычный терминал — как путь к файлу. Это Smart Clipboard: оба формата кладутся в буфер сразу.',
    logTitle: 'Журнал вызовов',
    logEmpty: 'Claude ещё не обращался к Shotik',
    logMs: '{0} мс',
    settingsTitle: 'Настройки',
    hkTitle: 'Горячие клавиши',
    hkRegion: 'Снимок области', hkRegionSub: 'выделение с аннотациями',
    hkFull: 'Весь экран', hkFullSub: 'монитор под курсором, сразу в буфер',
    hkRepeat: 'Переснять область', hkRepeatSub: 'та же область, свежие пиксели — идеально для итераций с Claude',
    hkPlaceholder: 'нажми сочетание',
    hkRecording: 'жми клавиши… (Esc — отмена, Del — убрать)',
    hkWarn: '⚠ Не удалось зарегистрировать: {0} — сочетание занято другим приложением.',
    saveTitle: 'Сохранение',
    saveDir: 'Папка снимков', btnChange: 'Изменить',
    autoSave: 'Автосохранение', autoSaveSub: 'каждый снимок сразу пишется в папку',
    clipTitle: 'Буфер обмена и удобства',
    smartClip: 'Smart Clipboard', smartClipSub: 'картинка + путь к файлу в буфере одновременно',
    toasts: 'Уведомления', toastsSub: 'тост после каждого снимка',
    downscale: 'Сжимать снимки для AI', downscaleSub: 'MCP отдаёт ≤1600px — быстрее и дешевле для Claude',
    autostart: 'Запуск с Windows', autostartSub: 'тихий старт в трей',
    language: 'Язык', languageSub: 'язык интерфейса',
    langSystem: 'Системный',
    mcpSettingsTitle: 'MCP-сервер',
    port: 'Порт', portSub: 'перезапустится автоматически',
  },
};

function resolveLang(setting, systemLocale) {
  if (setting === 'ru' || setting === 'en') return setting;
  return String(systemLocale || '').toLowerCase().startsWith('ru') ? 'ru' : 'en';
}

function makeT(lang) {
  const dict = DICTS[lang] || DICTS.en;
  return (key, ...args) => {
    let s = dict[key] !== undefined ? dict[key] : (DICTS.en[key] !== undefined ? DICTS.en[key] : key);
    args.forEach((a, i) => { s = s.split(`{${i}}`).join(String(a)); });
    return s;
  };
}

module.exports = { DICTS, resolveLang, makeT };
