'use strict';
// All UI strings. Language: settings.language = 'system' | 'en' | 'ru'.
// t(key, ...args) substitutes {0}, {1}, …

const DICTS = {
  en: {
    // tray
    trayTooltip: 'Shotik — screenshots for humans & AI',
    trayRecTooltip: 'Recording… — click to stop',
    trayRegion: 'Capture area',
    trayFull: 'Capture screen',
    trayRepeat: 'Repeat last area',
    trayText: 'Extract text',
    trayTranslate: 'Translate selection',
    trayRecord: 'Record area…',
    trayStopRec: 'Stop recording',
    trayOpen: 'Open Shotik',
    trayQuit: 'Quit',
    recSavedTitle: 'Recording saved',
    recSavedBody: 'Video · {0}',
    recFailTitle: 'Recording failed',
    // toasts
    copiedTitle: 'Copied to clipboard',
    noSave: 'Not saved to disk',
    claudeTitle: 'Ready for Claude',
    claudeBody: 'Ctrl+V in the console — pastes the image or the path',
    savedTitle: 'Saved',
    screenCopied: 'Screen copied',
    ocrDoneTitle: 'Text recognized and copied',
    ocrTitle: 'OCR',
    ocrNoText: 'No text found',
    ocrFailTitle: 'OCR failed',
    noLastTitle: 'No last area yet',
    noLastBody: 'Take an area screenshot first ({0})',
    repeatTitle: 'Area re-captured',
    colorTitle: 'Color copied',
    mcpFailTitle: 'MCP server failed to start',
    mcpFailBody: 'Port {0}: {1}',
    // pin context menu
    pinCopy: 'Copy image',
    pinSaveAs: 'Save as…',
    pinReveal: 'Show in folder',
    pinOpacity: 'Opacity {0}%',
    pinReset: 'Original size (100%)',
    pinClose: 'Close',
    // mac permission dialog
    permTitle: 'Shotik needs Screen Recording access',
    permBody: 'System Settings → Privacy & Security → Screen Recording → enable Shotik, then restart the app.',
    // overlay
    hintDrag: 'Drag', hintDragDesc: 'select area',
    hintClick: 'Click', hintClickDesc: 'window / screen',
    hintAlt: 'Shift+click', hintAltDesc: 'whole screen',
    hintColor: 'C', hintColorDesc: 'pick pixel color',
    hintEsc: 'Esc', hintEscDesc: 'cancel',
    claudeBadge: 'Claude is waiting — select an area and confirm',
    toolMove: 'Select (1)', toolPen: 'Pen (2)', toolArrow: 'Arrow (3)', toolLine: 'Line (4)',
    toolRect: 'Box (5)', toolEllipse: 'Ellipse (6)', toolHighlight: 'Highlighter (7)',
    toolBlur: 'Pixelate (8)', toolText: 'Text (9)', toolCounter: 'Numbering (0)',
    tipUndo: 'Undo (Ctrl+Z)', tipRedo: 'Redo (Ctrl+Y)',
    tipOcr: 'Extract text (T)', tipPin: 'Pin on top (P)', tipRec: 'Record video (V)', tipSave: 'Save as… (Ctrl+S)',
    tipClaude: 'Copy for Claude (A)', tipCopy: 'Copy (Enter)', tipCancel: 'Cancel (Esc)',
    tipThin: 'Thin ([)', tipMedium: 'Medium', tipThick: 'Thick (])',
    // Live Text mode
    txtRecognizing: 'Recognizing text…',
    txtCopy: 'Copy (Enter)', txtAll: 'Select all (Ctrl+A)', txtTranslate: 'Translate (R)', txtBack: 'Back (Esc)',
    txtTranslation: 'Translation', txtCopyTranslation: 'Copy translation',
    txtTranslating: 'Translating…', txtTranslateFail: 'Translation failed — check the connection.',
    // app: nav & gallery
    navShots: 'Shots', navClaude: 'Claude', navSettings: 'Settings',
    logoSub: 'screenshots for humans & AI',
    shotsTitle: 'Shots',
    btnRegion: 'Area', btnFull: 'Screen', btnRepeat: 'Repeat',
    tipRepeatBtn: 'Re-capture the last area — same coordinates, fresh pixels',
    tipOpenDir: 'Open screenshots folder',
    emptyTitle: 'No screenshots yet',
    emptyBody: 'Press {0} anytime — select an area and it lands<br>in your clipboard and in this gallery.',
    srcRegion: 'area', srcFullscreen: 'screen', srcRepeat: 'repeat', srcMcp: 'Claude', srcPin: 'pin',
    justNow: 'just now', minAgo: '{0} min ago', hourAgo: '{0} h ago',
    actCopy: 'Copy', actPath: 'Path', actPin: 'Pin', actOcr: 'OCR', actFolder: 'Folder', actDelete: 'Delete',
    actPlay: 'Play', actGif: 'Export GIF', actGifBusy: 'Making GIF…',
    btnRecord: 'Record', btnStopRec: 'Stop', tipRecordBtn: 'Record a region to video / GIF',
    srcRecord: 'video',
    recSecTitle: 'Screen recording',
    recFps: 'Frame rate', recFpsSub: 'higher is smoother but larger files',
    recFormat: 'Format', recFormatSub: 'WebM is reliable; MP4 depends on your system codecs',
    recAudio: 'System audio', recAudioSub: 'record the sound playing on your PC',
    recCountdown: '3-2-1 countdown', recCountdownSub: 'brief count before recording starts',
    gifReadyTitle: 'GIF ready', gifFailTitle: 'GIF export failed',
    // app: claude page
    claudePageTitle: 'Claude can see your screen',
    mcpCardTitle: 'Built-in MCP server',
    mcpRunning: 'Running at <b>http://127.0.0.1:{0}/mcp</b>',
    mcpNotRunning: 'Not running — the port may be busy',
    mcpDisabled: 'Disabled',
    connectTitle: 'Connect to Claude Code', connectOnce: 'one time',
    connectSub: 'After this, Claude can take screenshots of your screen by itself.',
    btnCopyCmd: 'Copy', btnCopiedCmd: 'Copied ✓',
    toolsTitle: 'What Claude can do through Shotik',
    toolDesc1: 'look at the screen right now',
    toolDesc2: 'ask you to select an area',
    toolDesc3: 'grab your latest screenshot',
    hintBox: '💡 A copied screenshot pastes into Claude Code as an image (<kbd>Ctrl+V</kbd>), and into a regular terminal as a file path. That’s Smart Clipboard: both formats go to the clipboard at once.',
    logTitle: 'Call log',
    logEmpty: 'Claude hasn’t called Shotik yet',
    logMs: '{0} ms',
    // app: settings page
    settingsTitle: 'Settings',
    hkTitle: 'Hotkeys',
    hkRegion: 'Capture area', hkRegionSub: 'selection with annotations',
    hkFull: 'Full screen', hkFullSub: 'monitor under the cursor, straight to clipboard',
    hkRepeat: 'Repeat last area', hkRepeatSub: 'same area, fresh pixels — perfect for iterating with Claude',
    hkText: 'Extract text', hkTextSub: 'select an area → grab and translate the text in it (Live Text)',
    hkRecord: 'Record area', hkRecordSub: 'select a region and record it to video / GIF (press again to stop)',
    hkTranslate: 'Translate selection', hkTranslateSub: 'select text in any app → instant translation, no screenshot',
    hkPlaceholder: 'press a shortcut',
    trNoSelTitle: 'No text selected', trNoSelBody: 'Select some text first, then press the shortcut',
    hkRecording: 'press keys… (Esc — cancel, Del — clear)',
    hkWarn: '⚠ Failed to register: {0} — the shortcut is taken by another app.',
    saveTitle: 'Saving',
    saveDir: 'Screenshots folder', btnChange: 'Change',
    autoSave: 'Auto-save', autoSaveSub: 'every shot is written to the folder immediately',
    clipTitle: 'Clipboard & convenience',
    smartClip: 'Smart Clipboard', smartClipSub: 'image + file path in the clipboard at the same time',
    toasts: 'Notifications', toastsSub: 'toast after every capture',
    downscale: 'Compress shots for AI', downscaleSub: 'MCP serves ≤1600px — faster and cheaper for Claude',
    autostart: 'Start with Windows', autostartSub: 'silent start in the tray',
    language: 'Language', languageSub: 'interface language',
    langSystem: 'System',
    mcpSettingsTitle: 'MCP server',
    port: 'Port', portSub: 'restarts automatically',
    trTitle: 'Text & translation',
    trTarget: 'Translate into', trTargetSub: 'target language for extracted text',
    trProvider: 'Translator', trProviderSub: 'free works out of the box; a DeepL key is more reliable',
    trProviderFree: 'Free (no key)', trProviderDeepl: 'DeepL (key)',
    trKey: 'DeepL API key', trKeySub: 'free tier gives 500k chars/month — key ends with :fx',
    trKeyPh: 'paste your key',
    trAutoBubble: 'Translate bubble on selection',
    trAutoBubbleSub: 'select text anywhere → a small button pops up; click it to translate (no clipboard, no screenshot)',
  },

  ru: {
    trayTooltip: 'Shotik — скриншоты для людей и AI',
    trayRecTooltip: 'Идёт запись… — клик, чтобы остановить',
    trayRegion: 'Снимок области',
    trayFull: 'Весь экран',
    trayRepeat: 'Переснять область',
    trayText: 'Вытащить текст',
    trayTranslate: 'Перевести выделение',
    trayRecord: 'Записать область…',
    trayStopRec: 'Остановить запись',
    trayOpen: 'Открыть Shotik',
    trayQuit: 'Выход',
    recSavedTitle: 'Запись сохранена',
    recSavedBody: 'Видео · {0}',
    recFailTitle: 'Запись не удалась',
    copiedTitle: 'Скопировано в буфер',
    noSave: 'Без сохранения',
    claudeTitle: 'Готово для Claude',
    claudeBody: 'Ctrl+V в консоль — вставится картинка или путь',
    savedTitle: 'Сохранено',
    screenCopied: 'Экран скопирован',
    ocrDoneTitle: 'Текст распознан и скопирован',
    ocrTitle: 'OCR',
    ocrNoText: 'Текст не найден',
    ocrFailTitle: 'OCR не сработал',
    noLastTitle: 'Нет последней области',
    noLastBody: 'Сначала сделай снимок области ({0})',
    repeatTitle: 'Область переснята',
    colorTitle: 'Цвет скопирован',
    mcpFailTitle: 'MCP-сервер не запустился',
    mcpFailBody: 'Порт {0}: {1}',
    pinCopy: 'Копировать изображение',
    pinSaveAs: 'Сохранить как…',
    pinReveal: 'Открыть в папке',
    pinOpacity: 'Прозрачность {0}%',
    pinReset: 'Исходный размер (100%)',
    pinClose: 'Закрыть',
    permTitle: 'Shotik нужен доступ к записи экрана',
    permBody: 'Системные настройки → Конфиденциальность и безопасность → Запись экрана → включить Shotik, затем перезапустить приложение.',
    hintDrag: 'Тяни', hintDragDesc: 'область',
    hintClick: 'Клик', hintClickDesc: 'окно / экран',
    hintAlt: 'Shift+клик', hintAltDesc: 'весь экран',
    hintColor: 'C', hintColorDesc: 'цвет пикселя',
    hintEsc: 'Esc', hintEscDesc: 'отмена',
    claudeBadge: 'Claude ждёт область — выдели и подтверди',
    toolMove: 'Выделение (1)', toolPen: 'Перо (2)', toolArrow: 'Стрелка (3)', toolLine: 'Линия (4)',
    toolRect: 'Рамка (5)', toolEllipse: 'Эллипс (6)', toolHighlight: 'Маркер (7)',
    toolBlur: 'Пикселизация (8)', toolText: 'Текст (9)', toolCounter: 'Нумерация (0)',
    tipUndo: 'Отменить (Ctrl+Z)', tipRedo: 'Вернуть (Ctrl+Y)',
    tipOcr: 'Вытащить текст (T)', tipPin: 'Закрепить поверх окон (P)', tipRec: 'Записать видео (V)', tipSave: 'Сохранить как… (Ctrl+S)',
    tipClaude: 'Скопировать для Claude (A)', tipCopy: 'Копировать (Enter)', tipCancel: 'Отмена (Esc)',
    tipThin: 'Тонко ([)', tipMedium: 'Средне', tipThick: 'Толсто (])',
    // Live Text mode
    txtRecognizing: 'Распознаю текст…',
    txtCopy: 'Копировать (Enter)', txtAll: 'Выделить всё (Ctrl+A)', txtTranslate: 'Перевести (R)', txtBack: 'Назад (Esc)',
    txtTranslation: 'Перевод', txtCopyTranslation: 'Копировать перевод',
    txtTranslating: 'Перевожу…', txtTranslateFail: 'Перевод не удался — проверь соединение.',
    navShots: 'Снимки', navClaude: 'Claude', navSettings: 'Настройки',
    logoSub: 'скриншоты для людей и AI',
    shotsTitle: 'Снимки',
    btnRegion: 'Область', btnFull: 'Экран', btnRepeat: 'Переснять',
    tipRepeatBtn: 'Переснять последнюю область — те же координаты, свежие пиксели',
    tipOpenDir: 'Открыть папку со снимками',
    emptyTitle: 'Пока нет снимков',
    emptyBody: 'Нажми {0} в любой момент — выдели область, и она окажется<br>в буфере обмена и в этой галерее.',
    srcRegion: 'область', srcFullscreen: 'экран', srcRepeat: 'повтор', srcMcp: 'Claude', srcPin: 'pin',
    justNow: 'только что', minAgo: '{0} мин назад', hourAgo: '{0} ч назад',
    actCopy: 'Копировать', actPath: 'Путь', actPin: 'Закрепить', actOcr: 'OCR', actFolder: 'В папке', actDelete: 'Удалить',
    actPlay: 'Воспроизвести', actGif: 'Экспорт в GIF', actGifBusy: 'Делаю GIF…',
    btnRecord: 'Запись', btnStopRec: 'Стоп', tipRecordBtn: 'Записать область в видео / GIF',
    srcRecord: 'видео',
    recSecTitle: 'Запись экрана',
    recFps: 'Частота кадров', recFpsSub: 'выше — плавнее, но файл больше',
    recFormat: 'Формат', recFormatSub: 'WebM надёжен; MP4 зависит от кодеков системы',
    recAudio: 'Системный звук', recAudioSub: 'записывать звук, играющий на ПК',
    recCountdown: 'Отсчёт 3-2-1', recCountdownSub: 'короткий отсчёт перед стартом записи',
    gifReadyTitle: 'GIF готов', gifFailTitle: 'Не удалось сделать GIF',
    claudePageTitle: 'Claude видит твой экран',
    mcpCardTitle: 'Встроенный MCP-сервер',
    mcpRunning: 'Работает на <b>http://127.0.0.1:{0}/mcp</b>',
    mcpNotRunning: 'Не запустился — возможно, порт занят',
    mcpDisabled: 'Выключен',
    connectTitle: 'Подключение к Claude Code', connectOnce: 'один раз',
    connectSub: 'После этого Claude сможет сам делать скриншоты твоего экрана.',
    btnCopyCmd: 'Копировать', btnCopiedCmd: 'Скопировано ✓',
    toolsTitle: 'Что умеет Claude через Shotik',
    toolDesc1: 'посмотреть на экран прямо сейчас',
    toolDesc2: 'попросить тебя выделить область',
    toolDesc3: 'взять твой последний снимок',
    hintBox: '💡 Скопированный снимок вставляется в Claude Code как картинка (<kbd>Ctrl+V</kbd>), а в обычный терминал — как путь к файлу. Это Smart Clipboard: оба формата кладутся в буфер сразу.',
    logTitle: 'Журнал вызовов',
    logEmpty: 'Claude ещё не обращался к Shotik',
    logMs: '{0} мс',
    settingsTitle: 'Настройки',
    hkTitle: 'Горячие клавиши',
    hkRegion: 'Снимок области', hkRegionSub: 'выделение с аннотациями',
    hkFull: 'Весь экран', hkFullSub: 'монитор под курсором, сразу в буфер',
    hkRepeat: 'Переснять область', hkRepeatSub: 'та же область, свежие пиксели — идеально для итераций с Claude',
    hkText: 'Вытащить текст', hkTextSub: 'выдели область → извлеки и переведи текст в ней (Live Text)',
    hkRecord: 'Запись области', hkRecordSub: 'выдели область и запиши её в видео / GIF (повторное нажатие — стоп)',
    hkTranslate: 'Перевести выделение', hkTranslateSub: 'выдели текст в любом приложении → мгновенный перевод, без скриншота',
    hkPlaceholder: 'нажми сочетание',
    trNoSelTitle: 'Текст не выделен', trNoSelBody: 'Сначала выдели текст, потом нажми сочетание',
    hkRecording: 'жми клавиши… (Esc — отмена, Del — убрать)',
    hkWarn: '⚠ Не удалось зарегистрировать: {0} — сочетание занято другим приложением.',
    saveTitle: 'Сохранение',
    saveDir: 'Папка снимков', btnChange: 'Изменить',
    autoSave: 'Автосохранение', autoSaveSub: 'каждый снимок сразу пишется в папку',
    clipTitle: 'Буфер обмена и удобства',
    smartClip: 'Smart Clipboard', smartClipSub: 'картинка + путь к файлу в буфере одновременно',
    toasts: 'Уведомления', toastsSub: 'тост после каждого снимка',
    downscale: 'Сжимать снимки для AI', downscaleSub: 'MCP отдаёт ≤1600px — быстрее и дешевле для Claude',
    autostart: 'Запуск с Windows', autostartSub: 'тихий старт в трей',
    language: 'Язык', languageSub: 'язык интерфейса',
    langSystem: 'Системный',
    mcpSettingsTitle: 'MCP-сервер',
    port: 'Порт', portSub: 'перезапустится автоматически',
    trTitle: 'Текст и перевод',
    trTarget: 'Переводить на', trTargetSub: 'язык, на который переводить извлечённый текст',
    trProvider: 'Переводчик', trProviderSub: 'бесплатный работает из коробки; ключ DeepL — надёжнее',
    trProviderFree: 'Бесплатный (без ключа)', trProviderDeepl: 'DeepL (по ключу)',
    trKey: 'API-ключ DeepL', trKeySub: 'бесплатный тариф — 500k символов/мес, ключ заканчивается на :fx',
    trKeyPh: 'вставь свой ключ',
    trAutoBubble: 'Пузырь перевода при выделении',
    trAutoBubbleSub: 'выдели текст где угодно → рядом всплывёт кнопка; клик — перевод (без буфера обмена и скриншота)',
  },
};

function resolveLang(setting, systemLocale) {
  if (setting === 'ru' || setting === 'en') return setting;
  return String(systemLocale || '').toLowerCase().startsWith('ru') ? 'ru' : 'en';
}

function makeT(lang) {
  const dict = DICTS[lang] || DICTS.en;
  return (key, ...args) => {
    let s = dict[key] !== undefined ? dict[key] : (DICTS.en[key] !== undefined ? DICTS.en[key] : key);
    args.forEach((a, i) => { s = s.split(`{${i}}`).join(String(a)); });
    return s;
  };
}

module.exports = { DICTS, resolveLang, makeT };
